baseURL = 'https://static.aaa-uspecq.com/'
languageCode = 'fr-fr'
title = 'AAA Static site'


[params]
description =  "Site web statique pour le club l'Association des Archers Alpicois."
footer =  "&copy; AAA 2025"

[markup]
  [markup.highlight]
    codeFences = true
  [markup.goldmark]
    duplicateResourceFiles = false
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
  [[module.mounts]]
    source = 'content'
    target = 'content'
  [[module.mounts]]
    source = 'static'
    target = 'static'
  [[module.mounts]]
    source = 'layouts'
    target = 'layouts'
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'archetypes'
    target = 'archetypes'
  [[module.mounts]]
    source = "node_modules/purecss/build"
    target = "assets/css/pure"
